
spring:
  application:
    name:
      activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ActivityFitness
      database: ActivityFitness


server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka