server:
  port: 8081
spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ActivityFitness
      database: ActivityFitness
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


