server:
  port: 8083
spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-recommendations
      database: fitness-recommendations

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

# let us hardcode this for now
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: AIzaSyBz1Ls11_ZsocBFcOuK0k7e654Xhi5KN-k

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
